# -*- coding: utf-8 -*-
"""correlation-grid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSdJ7icwyiWc50Pkpr_MaTJ1yMe5VGMR
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets

"""Prove that the data is clean with no null values."""

def get_correlation_grid():
    df = pd.read_csv('./data/Crop_recommendation.csv')
    print(df.isnull().sum())

    # Exclude non-numeric columns for the correlation matrix
    numeric_df = df.select_dtypes(include=['float64', 'int64'])

    # Calculate the correlation matrix
    correlation_matrix = numeric_df.corr()

    fig, ax = plt.subplots()

    # Plot the heatmap
    fig.set_size_inches(10, 8)
    sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap="RdBu", center=0,
                cbar=True, cbar_kws={'label': 'Correlation Coefficient'})
    ax.set_title('Correlation Heatmap of Features')
    
    return fig
